version: '3.4'
services:

  weaviate:
    image: semitechnologies/weaviate:1.24.4
    ports:
    - 8777:8080
    restart: unless-stopped
    volumes:
      - ${WEAVIATE_STORAGE_PATH:-./storage/weaviate}:/var/lib/weaviate
    environment:
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: 'none'
      QUERY_DEFAULTS_LIMIT: 25
      CLUSTER_HOSTNAME: 'node1'
      DISABLE_TELEMETRY: 'true'
      LIMIT_RESOURCES: 'true'

  semantic-search:
    image: ghcr.io/janeliascicomp/gpt-semantic-search:latest
    ports:
    - 8501:8501
    restart: unless-stopped
    environment:
      STREAMLIT_SERVER_FILE_WATCHER_TYPE: 'none'
      STREAMLIT_SERVER_HEADLESS: 'true'
      WEAVIATE_URL: 'http://weaviate:8080'
      OPENAI_API_KEY:
      SLACK_TOKEN:

  slack-bot:
    build:
      context: .
      dockerfile: Dockerfile_slack
    restart: unless-stopped
    environment:
      SLACK_BOT_TOKEN: 
      SLACK_APP_TOKEN: 
      WEAVIATE_URL: 'http://weaviate:8080'
      OPENAI_API_KEY: OPENAI_API_KEY
    depends_on:
      - weaviate




