version: '3.4'
services:

  weaviate:
    image: semitechnologies/weaviate:1.20.5
    ports:
    - 8080:8080
    restart: on-failure:0
    volumes:
      - ${WEAVIATE_STORAGE_PATH:-./storage/weaviate}:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'

  semantic-search:
    image: registry.int.janelia.org/scsw/semantic-search:1.0.4
    ports:
    - 8501:8501
    restart: on-failure:0
    environment:
      STREAMLIT_SERVER_FILE_WATCHER_TYPE: 'none'
      STREAMLIT_SERVER_HEADLESS: 'true'
      WEAVIATE_URL: 'http://weaviate:8080'
      OPENAI_API_KEY:
      SLACK_TOKEN:

